# Generated by Django 5.0.1 on 2024-01-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=10)),
                ('joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
