# Generated by Django 5.0.1 on 2024-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_member_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
