# Generated by Django 5.0.1 on 2024-01-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_description_member_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
